[package]
name = "rustdemo"
version = "0.1.0"
authors = ["Jorge Tim√≥n <jtimon@jtimon.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
